# Generated by Django 4.1.2 on 2023-07-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ShowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('age', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateField(null=True)),
                ('Current_ShowRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ShowRoomManagement.showroom')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ShowRoomManagement.role')),
            ],
        ),
    ]
