# Generated by Django 4.1.2 on 2023-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomManagement', '0002_feature_alter_role_name_carmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='cars',
            field=models.ManyToManyField(related_name='showrooms', to='ShowRoomManagement.carmodel'),
        ),
    ]
