# Generated by Django 4.1.2 on 2023-07-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomManagement', '0003_showroom_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cars',
        ),
        migrations.AddField(
            model_name='brand',
            name='cars',
            field=models.ManyToManyField(related_name='brand', to='ShowRoomManagement.carmodel'),
        ),
    ]
