# Generated by Django 4.1.2 on 2023-07-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomManagement', '0006_remove_brand_cars_brand_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cars',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='ShowRoomManagement.brand'),
        ),
    ]
