# Generated by Django 4.1.2 on 2023-07-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomManagement', '0008_alter_carmodel_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
