# Generated by Django 4.1.2 on 2023-07-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomManagement', '0012_alter_carmodel_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='engine',
        ),
    ]
