# Generated by Django 4.1.2 on 2023-07-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomManagement', '0014_carmodel_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='ShowRoomManagement.engine'),
        ),
    ]
